### ISSUE TITLE
Embedded version file is invalid

### ISSUE THREAD

**Issue by hakan42** [qfeys/ThrottleControlledAvionics#1]
CKAN tries to expand version information from the .version file. It stumbles over missing commas in the version string in your addon.

Could you, by any chance, change your version file to look like (also, please make sure that it is valid JSON, verifying especially the comma signs...

```
    "VERSION":
     {
         "MAJOR":2,
         "MINOR":0,
         "PATCH":0,
         "BUILD":0
     },
    "KSP_VERSION_MIN":
     {
         "MAJOR":0,
         "MINOR":90,
         "PATCH":0
     },
```

**Comment by allista** [comment]
The updated version will be included in the next release. I'll push the request to NetKAN with the updated .netkan file then.
