### ISSUE TITLE
Dethrottling occurs for a single engine when mode is set to main engine

### ISSUE THREAD

**Issue by masasin** [qfeys/ThrottleControlledAvionics#10]
I tried multiple craft, including ones where the engine is part of the pod, and a stack including a regular pod with separators and fuel tanks and a skipper.

When the main engine mode is set, dethrottling occurs occasionally. This happens both on orbit and on surfaces, including the launchpad. I have not figured out a specific cause.

**Comment by allista** [comment]
Sorry for late response.It is most likely to happen due to gimballing, as the thrust vector starts to point not through the CoM. What version are you using.

**Comment by masasin** [comment]
I am using 2.3.0.1 on KSP 1.0.4.

**Comment by allista** [comment]
Fixed in 495ea03f4837f860ec049f5f86ebc3048e19f63d by adding a separate "UnBalanced Thrust" mode. Use it for single engine configurations.
