### ISSUE TITLE
Yellow/green color choice not color-blind friendly

### ISSUE THREAD

**Issue by mathuin** [qfeys/ThrottleControlledAvionics#11]
I understand why you might not want to use red for disabled functionality.  What about blue?  The yellow currently used looks the same as the green to me. :-(

**Comment by allista** [comment]
To my shame, I became conscious about this problem only this week when another guy with the same problem accidentally told about it on the forums.
As a quick fix you can grab the patches DLLs that i made for him from the last pages of the forum. They use red-green scheme.
The more permanent solution - customizable color scheme defined in a config file - is already committed and will be included in the next update.

**Comment by allista** [comment]
Here's a direct link to the patches:
https://www.dropbox.com/s/z0upmbp8wjgk8h3/TCA-red-green-buttons.zip?dl=0

**Comment by mathuin** [comment]
Wow, awesome, thank you so much.  I am really excited about the upcoming improvement in usability.  I'll try the patches at home to see how they work!

**Comment by allista** [comment]
Closed with commit f48ff89.
The new version is available for both KSP-1.0.5 and 1.1.2.
Also, I encourage you to read [this section of the Manual](https://github.com/qfeys/ThrottleControlledAvionics/blob/master/GameData/ThrottleControlledAvionics/INSTRUCTIONS.md#tcaglob--the-global-tca-settings) to understand how to override global settings.
