### ISSUE TITLE
CKAN issue with 000_AT_Utils

### ISSUE THREAD

**Issue by jrodrigv** [qfeys/ThrottleControlledAvionics#13]
Hi there,

First of all, thanks for your great on this mod.

I just found one issue getting the last version by CKAN. AT_Utils is not defined as a dependency and It is not in CKAN yet so it can't work properly at the moment.

Kind Regards,

Jesus

**Comment by allista** [comment]
Unfortunately, yes. You'll have to install TCA manually until I'm able to release the Utils library. The library is included in TCA release.

**Comment by shadowdargonRU** [comment]
Allis Tauri Твой мод не работает  Throttle Controlled Avionics Всё перепробовал как вообще его запустить в сандбоксе 
Your mod is not working http://spacedock.info/mod/198/Throttle%20Controlled%20Avionics All pereprobyval as generally its launch in sandbokse

**Comment by allista** [comment]
Fixed that with the manually maintained CKAN metadata for TCA and AT_Utils.
