### ISSUE TITLE
Exception caused by TCA

### ISSUE THREAD

**Issue by Galenmacil** [qfeys/ThrottleControlledAvionics#21]
Here and excerpt from the log file:

_[EXC 22:14:51.467] NullReferenceException: Object reference not set to an instance of an object
	AT_Utils.Utils.PartIsPurchased (System.String name)
	ThrottleControlledAvionics.TCAModulesDatabase.ModuleAvailable (System.Type m)
	ThrottleControlledAvionics.EnginesProfileEditor.Awake ()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	AddonLoader:OnLevelLoaded(Int32)
	AddonLoader:OnSceneLoaded(Scene, LoadSceneMode)
	UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)_

**Comment by allista** [comment]
Thanks for the report!

**Comment by allista** [comment]
Fixed upstream:
https://github.com/allista/AT_Utils/commit/27921d8c4a0e9c80516ce54863981e1c20064b5d
