### ISSUE TITLE
Request: Auto disable TCA on electricity depleted

### ISSUE THREAD

**Issue by m9731526** [qfeys/ThrottleControlledAvionics#24]
When a craft is uncontrollable (e.g. no signal), the TCA interface will be disabled.

And if TCA is allowed to warp, when the interface is disabled and the craft is running out of electricity, because TCA will warp when electricity is available and soon use up all the power in seconds, users have no chance to rotate the craft to have better sunlight exposure or use the reserve power provided by AmpYear mod, neither disable warping of TCA.

**Comment by allista** [comment]
TCA is in fact disabled on electricity depletion. It just has to stop the warp when it happens.

**Comment by allista** [comment]
Should be fixed in v3.2.5.
