### ISSUE TITLE
Exception related to interaction with RemoteTech

### ISSUE THREAD

**Issue by Galenmacil** [qfeys/ThrottleControlledAvionics#26]
[ERR 18:27:54.580] Exception handling event onVesselWasModified in class ModuleTCA:System.NullReferenceException: Object reference not set to an instance of an object
  at ThrottleControlledAvionics.ModuleTCA.AllTCA (IShipconstruct ship) [0x00000] in <filename unknown>:0 
  at ThrottleControlledAvionics.ModuleTCA.updateCFG () [0x00000] in <filename unknown>:0 
  at ThrottleControlledAvionics.ModuleTCA.init () [0x00000] in <filename unknown>:0 
  at ThrottleControlledAvionics.ModuleTCA.onVesselModify (.Vessel vsl) [0x00000] in <filename unknown>:0 
  at EventData`1[Vessel].Fire (.Vessel data) [0x00000] in <filename unknown>:0 

[EXC 18:27:54.582] NullReferenceException: Object reference not set to an instance of an object
    ThrottleControlledAvionics.ModuleTCA.AllTCA (IShipconstruct ship)
    ThrottleControlledAvionics.ModuleTCA.updateCFG ()
    ThrottleControlledAvionics.ModuleTCA.init ()
    ThrottleControlledAvionics.ModuleTCA.onVesselModify (.Vessel vsl)
    EventData`1[Vessel].Fire (.Vessel data)
    UnityEngine.Debug:LogException(Exception)
    EventData`1:Fire(Vessel)
    RemoteTech.Modules.ModuleRTAntenna:AddTransmitter()
    RemoteTech.Modules.ModuleRTAntenna:SetState(Boolean)
    RemoteTech.Modules.ModuleRTAntenna:OnStart(StartState)
    Part:ModulesOnStart()
    <Start>c__Iterator38:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by allista** [comment]
Thank you for the report.
Could you describe the in-game situation that caused this?

**Comment by Galenmacil** [comment]
I tried to replicate this problem but was unable to... weird. Keep the issue open I'll do more testing it is bound to re-happen at some point. Thanks.

**Comment by allista** [comment]
Should be fixed in the v3.3.0

**Comment by allista** [comment]
Closing as inactive and most likely fixed.
