### ISSUE TITLE
The black kraken - Look rotation viewing vector is zero 

### ISSUE THREAD

**Issue by jrodrigv** [qfeys/ThrottleControlledAvionics#27]
Hi, 

First of all, thanks for this awesome mod. 

I have done a fresh install of KSP just to reproduce this issue. Only TCA v3.3.0 from github is installed.

Issue description: When set hover to 2000 m after few seconds, everything goes black.

Steps to reproduce the issue:

1. Clean KSP 1.2.1 installation and TCA v3.3.0
2. Download and launch this simple stock craft modified to be VTOL
[Stearwing A300 VTOL.zip](https://github.com/qfeys/ThrottleControlledAvionics/files/631148/Stearwing.A300.VTOL.zip)
3. Open TCA UI and set Enable and Hover to 2000m.
4. Stage engines.
5. Enjoy the kraken.

Find the log below:

[KSP.zip](https://github.com/qfeys/ThrottleControlledAvionics/files/631169/KSP.zip)

Kind Regards,
jrodriguez

**Comment by gomker** [comment]
I have seen the same effects when using TCA with helicopters. A few moments after setting Hover world goes black, map view no longer shows Kerbin

**Comment by androidfanman** [comment]
I also seem to have the same problem. I Did a fresh install of KSP, and just installed TCA 3.3.0. My screen goes black at around 200m though.

**Comment by allista** [comment]
Thank you for the steps-to-reproduce!!!
I was finally able to do it on my install. So no I'll be hunting it down.
