### ISSUE TITLE
Engine type cannot be change in 2.0.0+

### ISSUE THREAD

**Issue by crozone** [qfeys/ThrottleControlledAvionics#8]
Options for changing the engine type (Main, Maneuver, Manual) do not appear in the part menu in either the editor or while in flght.

**Comment by allista** [comment]
Have you installed ModuleManager? This option is injected via MM as a separate PartModule.

**Comment by crozone** [comment]
D'oh!

All working well with ModuleManager installed, my apologies. Closing.
